set terminal postscript eps color
set key inside left top vertical Right box
set output "blocksize.eps"

set bar 1.0
set boxwidth 1.9 absolute
set style fill   solid 1.00 border -1
set style rectangle back fc lt -3 fillstyle  solid 1.00 border -1

set title "Array Multiplication using different block sizes"
set xlabel "Block size"
set ylabel "Time"

set size 1, 0.7

#set yrange [ 0.00000 : 10. ] noreverse nowriteback

plot "blocksize.dat" using 2:xtic(1) notitle with lines
